name: Development Pipeline

on:
  push:
    branches: [develop]

jobs:
  lintTest:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          echo "Running Installing Dependencies..."
          npm install
      - name: Run linting
        run: |
          echo "Running linting test..."
          npm run lint
        env:
          CI: true
  securityCheck:
    name: Security Check
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Check for security
        run: |
          echo "Running Security Checks..."
          sleep 5s
          echo "Running Security Checks... 1"
          sleep 5s
          echo "Running Security Checks... 2"
          sleep 5s
          echo "Running Security Checks... 3"
          sleep 5s

  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    needs: [lintTest, securityCheck]
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          echo "Deployment in Progress..."
